# Generated by Django 5.0.4 on 2024-04-12 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_contact'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='User_Contact',
        ),
    ]
