# Generated by Django 5.0.4 on 2024-04-12 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rename_contact_user_contact'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User_Contact',
            new_name='Contact',
        ),
    ]
