# Generated by Django 5.0.4 on 2024-04-12 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp2', '0003_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='email',
            new_name='t_email',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='message',
            new_name='t_message',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='name',
            new_name='t_name',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='number',
            new_name='t_number',
        ),
    ]
