# Generated by Django 5.0.4 on 2024-04-12 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp2', '0005_rename_t_email_contact_email_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='TContact',
        ),
    ]
