# Generated by Django 5.0.4 on 2024-04-12 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp2', '0007_rename_tcontact_contact'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='DContact',
        ),
    ]
