# Generated by Django 5.0.4 on 2024-04-12 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp2', '0008_rename_contact_dcontact'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DContact',
            new_name='Contacts',
        ),
    ]
