# Generated by Django 5.0.4 on 2024-04-12 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp2', '0010_rename_contacts_delivery_contacts'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Delivery_Contacts',
            new_name='Contacts',
        ),
    ]
